const INCOME_CATEGORIES = [
  "Job",
  "Side project",
  "Tax refund",
  "Expense reimbursement",
  "Other",
  "Savings",
  "FHSA",
  "Recycle",
  "Cash on Hand",
  "EI",
  "Child Care Benefit",
];

const EXPENSE_CATEGORIES = [
  "Car maintenance",
  "Lessons",
  "Childcare",
  "Membership",
  "Condo fees",
  "Debt",
  "Electronics",
  "Entertainment",
  "Gas",
  "Gifts",
  "Subscriptions",
  "Groceries",
  "Parents",
  "Home maintenance",
  "Insurance",
  "Medical",
  "Mortgage",
  "Other",
  "Public transportation",
  "Rent",
  "Restaurant",
  "Telecom",
  "Travel",
  "Utilities",
  "Work",
  "Bank Charges",
  "Shopping",
  "Investment",
  "Transfer to Savings",
  "Transfer to FHSA",
  "Toys",
  "Furnitures",
  "Fitness",
  "Haircut",
];

export const Constants = {
  EXPENSE_CATEGORIES,
  INCOME_CATEGORIES,
};
