import {
  Category,
  CategoryTypes,
} from "./app/categories/_types/category.model";

const INCOME_CATEGORIES: Category[] = [
  {
    name: "Salary",
    categoryType: CategoryTypes.INCOME,
    id: "income-salary-001",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Freelance",
    categoryType: CategoryTypes.INCOME,
    id: "income-freelance-002",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Investments",
    categoryType: CategoryTypes.INCOME,
    id: "income-investments-003",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Job",
    categoryType: CategoryTypes.INCOME,
    id: "income-job-004",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Side project",
    categoryType: CategoryTypes.INCOME,
    id: "income-sideproject-005",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Tax refund",
    categoryType: CategoryTypes.INCOME,
    id: "income-taxrefund-006",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Expense reimbursement",
    categoryType: CategoryTypes.INCOME,
    id: "income-reimbursement-007",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Other",
    categoryType: CategoryTypes.INCOME,
    id: "income-other-008",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Savings",
    categoryType: CategoryTypes.INCOME,
    id: "income-savings-009",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "FHSA",
    categoryType: CategoryTypes.INCOME,
    id: "income-fhsa-010",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Recycle",
    categoryType: CategoryTypes.INCOME,
    id: "income-recycle-011",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Cash on Hand",
    categoryType: CategoryTypes.INCOME,
    id: "income-cashonhand-012",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "EI",
    categoryType: CategoryTypes.INCOME,
    id: "income-ei-013",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Child Care Benefit",
    categoryType: CategoryTypes.INCOME,
    id: "income-childcarebenefit-014",
    createdAt: new Date(),
    isActive: true,
  },
];

const EXPENSE_CATEGORIES: Category[] = [
  {
    name: "Car maintenance",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-carmaintenance-001",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Lessons",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-lessons-002",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Childcare",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-childcare-003",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Membership",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-membership-004",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Condo fees",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-condofees-005",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Debt",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-debt-006",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Electronics",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-electronics-007",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Entertainment",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-entertainment-008",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Gas",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-gas-009",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Gifts",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-gifts-010",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Subscriptions",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-subscriptions-011",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Groceries",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-groceries-012",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Parents",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-parents-013",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Home maintenance",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-homemaintenance-014",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Insurance",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-insurance-015",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Medical",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-medical-016",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Mortgage",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-mortgage-017",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Other",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-other-018",
    createdAt: new Date(),
    isActive: true,
  },
  {
    name: "Public transportation",
    categoryType: CategoryTypes.EXPENSE,
    id: "expense-publictransport-019",
    createdAt: new Date(),
    isActive: true,
  },
];

export const Constants = {
  EXPENSE_CATEGORIES,
  INCOME_CATEGORIES,
};
